services:
  nats:
    image: nats:2.11-alpine
    container_name: nats
    restart: always
    ports:
      - 4222:4222
    volumes:
      - ./data/nats:/data
    command: -js -sd /data
  nats-ui:
    image: ghcr.io/nats-nui/nui:0.6
    container_name: nats-ui
    ports:
      - 31311:31311
    volumes:
      - ./data/nats-ui:/db
